name: Deploy to gh-pages

on:
  push:
    branches:
      - main  # Se activa cuando se hace push a la rama main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Build React app
        run: npm run build

      - name: Deploy to gh-pages
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: npx gh-pages -d build -t true -a -m "Deploy to gh-pages"
